server:
  port: 8080
  
#
#spring:
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          "[0]":
#            allowed-origins: "http://localhost:3000"
#            allowed-methods: "GET,POST,PUT,DELETE"
#            allowed-headers: "*"
#            allow-credentials: true
  

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authservice
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/auth/**
        - id: shopService
          uri: lb://SHOP-SERVICE
          predicates:
            - Path=/shop/**
          filters:
            - AuthenticationFilter
        - id: customerservice
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/customer/**
          filters:
            - AuthenticationFilter
        - id: authservice
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/employee/**
          filters:
            - AuthenticationFilter
      globalcors:
        cors-configurations:
         "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "Content-Type,Authorization"
        
  application:
    name: gateway
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
